# Generated by Django 5.0.3 on 2024-05-31 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(default='General', max_length=100)),
                ('horacreado', models.DateTimeField(default=django.utils.timezone.now)),
                ('horaactualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
