# Generated by Django 5.0.3 on 2024-06-17 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioNuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('horaregistro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
